# *********************************
# *** Author: Enosis Technology ***
# *** Date:   03/04/2026        ***
# *** Update: 03/04/2026        ***
# *** License: AGPL-3-or-later  ***
# *********************************

# *************
# *** Files ***
# *************

SOURCE_FILES_WEBSOCKET = files(
	'Order.cpp',
	'Client.cpp'
)

libsxmm_websocket = static_library(
	'sxmm_order',

	SOURCE_FILES_WEBSOCKET,

	dependencies: dependencies,
	include_directories: search_inc
)