# *******************************
# *** Autor: PZH Gesellschaft ***
# *** Datum: 08. Juli. 2026   ***
# *** Aktua: 08. Juli. 2026   ***
# *** Lizenz: AGPL-3-or-later ***
# *******************************

SOURCE_FILES_WEBSOCKET_CLIENT_ORDERS = files(
	'bracketSample.cpp',
	'conditionSamples.cpp',
	'hedgeSample.cpp',
	'ibkratsSample.cpp',
	'ocaSamples.cpp',
	'orderOperations.cpp',
	'whatIfSamples.cpp'
)