# ********************************
# *** Author: Dracma Capital   ***
# *** Date:   03/04/2026       ***
# *** Update: 03/04/2026       ***
# *** License: AGPL-3-or-later ***
# ********************************

# ***************
# *** C files ***
# ***************

C_FILES_ORDER = files(
					'order.c'
				)

# *****************
# *** Cpp files ***
# *****************

CPP_FILES_ORDER = files(
						'main.cpp'
					)