# *******************************
# *** Autor: Reymon Dev       ***
# *** Datum: 08. Juli. 2026   ***
# *** Aktua: 24. Juli. 2026   ***
# *** Lizenz: AGPL-3-or-later ***
# *******************************

SOURCE_FILES_CLIENT_TIME= files(
	'currentTime.cpp',
	'currentTimeInMillis.cpp',
	'headTimestamp.cpp',
	'reqCurrentTime.cpp',
	'tickByTickAllLast.cpp',
	'wshCalendarOperations.cpp',
	'wshEventData.cpp',
	'wshMetaData.cpp'
)