# ********************************
# *** Author: Enosis Technology   ***
# *** Date:   03/04/2026       ***
# *** Update: 03/04/2026       ***
# *** License: AGPL-3-or-later ***
# ********************************

# *************
# *** Files ***
# *************

SOURCE_FILES_REPORT = files(
	'generate.c'
)

libsxmm_report = static_library(
	'sxmm_report',

	SOURCE_FILES_REPORT,

	dependencies: dependencies,
	include_directories: search_inc
)