# *******************************
# *** Autor: Reymon Dev       ***
# *** Datum: 08. Juli. 2026   ***
# *** Aktua: 08. Juli. 2026   ***
# *** Lizenz: AGPL-3-or-later ***
# *******************************

SOURCE_FILES_CLIENT_TICKER = files(
	'tickByTickBidAsk.cpp',
	'tickByTickMidPoint.cpp',
	'tickDataOperation.cpp',
	'tickEFP.cpp',
	'tickGeneric.cpp',
	'tickOptionComputation.cpp',
	'tickOptionComputationOperation.cpp',
	'tickReqParams.cpp',
	'tickSize.cpp',
	'tickSnapshotEnd.cpp',
	'tickString.cpp'
)