# *******************************
# *** Autor: PZH Gesellschaft ***
# *** Datum: 03/04/2026       ***
# *** Aktua: 03/04/2026       ***
# *** Lizenz: AGPL-3-or-later ***
# *******************************

# *************
# *** Files ***
# *************

SOURCE_FILES_REPORT_EXCEPTIONS = files(
	'general.cpp'
)