# *******************************
# *** Autor: Reymon Dev       ***
# *** Datum: 08. Juli. 2026   ***
# *** Aktua: 08. Juli. 2026   ***
# *** Lizenz: AGPL-3-or-later ***
# *******************************

SOURCE_FILES_CLIENT_CONNECTION = files(
	'connect.cpp',
	'connectAck.cpp',
	'connectionClosed.cpp',
	'disconnect.cpp',
	'ibkr_connection.cpp',
	'isConnected.cpp'
)