# *******************************
# *** Autor: Reymon Dev       ***
# *** Datum: 08. Juli. 2026   ***
# *** Aktua: 08. Juli. 2026   ***
# *** Lizenz: AGPL-3-or-later ***
# *******************************

SOURCE_FILES_CLIENT_OTHER = files(
	'deltaNeutralValidation.cpp',
	'displayGroupList.cpp',
	'displayGroupUpdated.cpp',
	'execDetails.cpp',
	'execDetailsEnd.cpp',
	'familyCodes.cpp',
	'receiveFA.cpp',
	'replaceFAEnd.cpp',
	'securityDefinitionOptionalParameter.cpp',
	'securityDefinitionOptionalParameterEnd.cpp',
	'smartComponents.cpp',
	'softDollarTiers.cpp',
	'verifyAndAuthCompleted.cpp',
	'verifyAndAuthMessageAPI.cpp',
	'verifyCompleted.cpp'
)