# *******************************
# *** Autor: Reymon Dev       ***
# *** Datum: 23. Juli. 2026   ***
# *** Aktua: 23. Juli. 2026   ***
# *** Lizenz: AGPL-3-or-later ***
# *******************************

# *****************
# *** Main Rule ***
# *****************

all: object libraries executable

# *******************
# *** Clean Rules ***
# *******************

clean:
	rm -f $(OBJECT_FILES) $(OBJECT_FILES_AS) $(OBJECT_FILES_CLIENT) $(OBJECT_FILES_REPORT) $(OBJECT_FILES_UTILS)
	rm -f $(SONAME_FILE_SHARED_LIBSXMM_AS) $(BINARY_FILE_SHARED_LIBSXMM_AS) $(MINOR_FILE_SHARED_LIBSXMM_AS) $(LINK_FILE_SHARED_LIBSXMM_AS)
	rm -f $(SONAME_FILE_SHARED_LIBSXMM_CLIENT) $(BINARY_FILE_SHARED_LIBSXMM_CLIENT) $(MINOR_FILE_SHARED_LIBSXMM_CLIENT) $(LINK_FILE_SHARED_LIBSXMM_CLIENT)
	rm -f $(SONAME_FILE_SHARED_LIBSXMM_REPORT) $(BINARY_FILE_SHARED_LIBSXMM_REPORT) $(MINOR_FILE_SHARED_LIBSXMM_REPORT) $(LINK_FILE_SHARED_LIBSXMM_REPORT)
	rm -f $(SONAME_FILE_SHARED_LIBSXMM_UTILS) $(BINARY_FILE_SHARED_LIBSXMM_UTILS) $(MINOR_FILE_SHARED_LIBSXMM_UTILS) $(LINK_FILE_SHARED_LIBSXMM_UTILS)
	rm -f $(BINARY_FILE_EXECUTABLE_SXMM)

distclean:
	rm -rf ./build/make

# ****************************
# *** Debug and test rules ***
# ****************************

run: $(BINARY_FILE_EXECUTABLE_SXMM)
	@./$<

run-gdb: $(BINARY_FILE_EXECUTABLE_SXMM)
	@gdb $<

# *********************
# *** Compile Rules ***
# *********************

object: $(OBJECT_FILES) $(OBJECT_FILES_AS) $(OBJECT_FILES_CLIENT) $(OBJECT_FILES_REPORT) $(OBJECT_FILES_UTILS)

libraries:	$(BINARY_FILE_STATIC_LIBSXMM_AS) $(BINARY_FILE_STATIC_LIBSXMM_CLIENT) $(BINARY_FILE_STATIC_LIBSXMM_REPORT) $(BINARY_FILE_STATIC_LIBSXMM_UTILS) \
			$(BINARY_FILE_SHARED_LIBSXMM_AS) $(MINOR_FILE_SHARED_LIBSXMM_AS) $(LINK_FILE_SHARED_LIBSXMM_AS) \
			$(BINARY_FILE_SHARED_LIBSXMM_REPORT) $(MINOR_FILE_SHARED_LIBSXMM_REPORT) $(LINK_FILE_SHARED_LIBSXMM_REPORT) \
			$(BINARY_FILE_SHARED_LIBSXMM_UTILS) $(MINOR_FILE_SHARED_LIBSXMM_UTILS) $(LINK_FILE_SHARED_LIBSXMM_UTILS) \
			$(BINARY_FILE_SHARED_LIBSXMM_CLIENT) $(MINOR_FILE_SHARED_LIBSXMM_CLIENT) $(LINK_FILE_SHARED_LIBSXMM_CLIENT)

executable: $(BINARY_FILE_EXECUTABLE_SXMM)