# *******************************
# *** Autor: PZH Gesellschaft ***
# *** Datum: 08. Juli. 2026   ***
# *** Aktua: 08. Juli. 2026   ***
# *** Lizenz: AGPL-3-or-later ***
# *******************************

SOURCE_FILES_WEBSOCKET_CLIENT_TICKER = files(
	'tickDataOperation.cpp',
	'tickEFP.cpp',
	'tickGeneric.cpp',
	'tickOptionComputationOperation.cpp',
	'tickSize.cpp',
	'tickSnapshotEnd.cpp',
	'tickString.cpp'
)