# *******************************
# *** Autor: PZH Gesellschaft ***
# *** Datum: 23. Juni. 2026   ***
# *** Aktua: 23. Juni. 2026   ***
# *** Lizenz: AGPL-3-or-later ***
# *******************************

# **********************
# *** Subdirectories ***
# **********************

subdir('other')
subdir('market')
subdir('historical')
subdir('codes')
subdir('analysis')
subdir('pnl')
subdir('time')
subdir('news')
subdir('price')
subdir('scanner')
subdir('id')
subdir('options')
subdir('client')
subdir('account')
subdir('advisor')
subdir('connection')
subdir('ticker')
subdir('protobuf')
subdir('contract')
subdir('test')
subdir('orders')
subdir('system')
subdir('bond')
subdir('error')
subdir('miscellaneous')

# ********************
# *** Source Files ***
# ********************

SOURCE_FILES_WEBSOCKET_CLIENT = [
	SOURCE_FILES_WEBSOCKET_CLIENT_ACCOUNT,
	SOURCE_FILES_WEBSOCKET_CLIENT_ADVISOR,
	SOURCE_FILES_WEBSOCKET_CLIENT_ANALYSIS,
	SOURCE_FILES_WEBSOCKET_CLIENT_BOND,
	SOURCE_FILES_WEBSOCKET_CLIENT_CLIENT,

	SOURCE_FILES_WEBSOCKET_CLIENT_CODES,
	SOURCE_FILES_WEBSOCKET_CLIENT_CONNECTION,
	SOURCE_FILES_WEBSOCKET_CLIENT_CONTRACT,
	SOURCE_FILES_WEBSOCKET_CLIENT_ERROR,
	SOURCE_FILES_WEBSOCKET_CLIENT_HISTORICAL,
	
	SOURCE_FILES_WEBSOCKET_CLIENT_ID,
	SOURCE_FILES_WEBSOCKET_CLIENT_MARKET,
	SOURCE_FILES_WEBSOCKET_CLIENT_MISCELLANEOUS,
	SOURCE_FILES_WEBSOCKET_CLIENT_NEWS,
	SOURCE_FILES_WEBSOCKET_CLIENT_OPTIONS,

	SOURCE_FILES_WEBSOCKET_CLIENT_ORDERS,
	SOURCE_FILES_WEBSOCKET_CLIENT_OTHER,
	SOURCE_FILES_WEBSOCKET_CLIENT_PNL,
	SOURCE_FILES_WEBSOCKET_CLIENT_PRICE,
	SOURCE_FILES_WEBSOCKET_CLIENT_PROTOBUF,

	SOURCE_FILES_WEBSOCKET_CLIENT_SCANNER,
	SOURCE_FILES_WEBSOCKET_CLIENT_SYSTEM,
	SOURCE_FILES_WEBSOCKET_CLIENT_TEST,
	SOURCE_FILES_WEBSOCKET_CLIENT_TICKER,
	SOURCE_FILES_WEBSOCKET_CLIENT_TIME
]