# *******************************
# *** Autor: PZH Gesellschaft ***
# *** Datum: 08. Juli. 2026   ***
# *** Aktua: 08. Juli. 2026   ***
# *** Lizenz: AGPL-3-or-later ***
# *******************************

SOURCE_FILES_WEBSOCKET_CLIENT_HISTORICAL = files(
	'historicalDataRequests.cpp',
	'reqHeadTimestamp.cpp',
	'reqHistogramData.cpp',
	'reqHistoricalNews.cpp',
	'reqHistoricalTicks.cpp',
	'reqTickByTickData.cpp'
)